### ISSUE TITLE
The game doesn't launch Exit with returncode 13568

### ISSUE THREAD

**Issue by Axeltherabbit** [Toetje585/Age-of-Empires-Online-Lutris#1]
```
lutris-wrapper: Age of Empires Online
Running /home/axel/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/bin/wine /home/axel/Games/age-of-empires-online/drive_c/Program Files/Age Of Empires Online/Spartan.exe --email xxxx --password xxx
Initial process has started with pid 1249
Game is considered started.
esync: up and running.
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 13568

```
Not sure if I have to apply the Celeste patch by myself, or whatelse I need to do, I have tried to tweak a bit the options but doesn't work. I don't see any useful log

`Linux xyz 5.9.8-arch1-1  x86_64 GNU/Linux`
`nvidia 455.38-7`

**Comment by Toetje585** [comment]
Hello, 

We did some work on patching the game in linux however we are having a few small issues left to take care off. in order to start the game you will need a fully patched working game from a windows machine for now.

**Comment by Axeltherabbit** [comment]
I see, thank you,  can you pass me a zip with the files by any chance?

**Comment by Toetje585** [comment]
> I see, thank you, you can pass me a zip with the files by any chance?

Add me to Discord or send me an email to get a link.

Discord: TerrorToetje#2457
Email: contact@msteinbusch.nl

**Comment by Nowa-Ammerlaan** [comment]
Could you perhaps specify in the `README.md` that running the "Update" step is required directly the "Setup" step to actually be able to launch the game. I just hit this problem as well and from the text it is currently not immediately clear that launching directly after completing the "Setup" phase will not work. Took quite some time before I found this issue and discovered the solution.
