### ISSUE TITLE
The script looks for game files in the local network rather than download them

### ISSUE THREAD

**Issue by Axeltherabbit** [Toetje585/Age-of-Empires-Online-Lutris#2]
https://github.com/Toetje585/Age-of-Empires-Online-Lutris/blob/d18463f45f42f4cececc1d3c9306079ba11be2b0/age-of-empires-online.yaml#L16
Not sure why, maybe I'm missing something, the README is not clear about it.
thank you.

**Comment by Toetje585** [comment]
Yes the script is not done yet and this will get replaced in future, I zipped my game and placed it into a local apache2 server.

**Comment by Toetje585** [comment]
Moved the installer to my own server, should be fine now!
