### ISSUE TITLE
http://168.119.211.214/AOEO_Installer.zip cannot be found

### ISSUE THREAD

**Issue by bse4792** [Toetje585/Age-of-Empires-Online-Lutris#5]
Hi, please make installationfile available again.

**Comment by Toetje585** [comment]
Hello,

This should work again it was caused due a faulty configuration of the web-server.

Let me know if you need any help!

**Comment by Nowa-Ammerlaan** [comment]
It is offline again, I instead downloaded the file manually from here: https://www.projectceleste.com/install/ --> (AOEO_Setup.exe, contrary to what the name suggests this downloads a zip not an exe) http://www.mediafire.com/file/afo6kcizm5qhl4e/AOEO_Installer.zip
