### ISSUE TITLE
Installation does not continue after "load andale"

### ISSUE THREAD

**Issue by Leonard-Reuter** [Toetje585/Age-of-Empires-Online-Lutris#6]
I am on Ubuntu 20.04 and tried to follow all the instructions given here. The installation seems to start succesfully, but it does not continue at some point, resting at:

Executing load_andale 
Executing cabextract -q -d /home/myname/Games/age-of-empires-online/dosdevices/c:/windows/temp /home/myname/.cache/winetricks/corefonts/andale32.exe

Is there any way to solve this? Thanks a lot!

**Comment by Skaifer** [comment]
I guess project is abandoned

**Comment by Toetje585** [comment]
I guess this is winetricks problem, try to update winetricks or try to remove the game and rerun the installation.

**Comment by SamPixelYork** [comment]
I had this exact issue today on Linux Mint 21 (Ubuntu base 22.04). After cancelling the installation and trying again, it worked on the third attempt. It still looked like it froze at "andale" but it eventually did continue
